#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1";

DOMAINS_FILE="$DOKKU_ROOT/$APP/DOMAINS"

if [[ -f "$DOMAINS_FILE" ]]; then
  DOMAINS=$(< "$DOMAINS_FILE")

  # update app nginx.conf with the current domains
  sed -i -r "s/server_name ([^; \n\t]*)([^;]*)(;?)/server_name \1 $DOMAINS;/" $DOKKU_ROOT/$APP/nginx.conf

fi