#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; PORT="$2";

DOMAINS_FILE="$DOKKU_ROOT/$APP/DOMAINS"

if [[ -f "$DOMAINS_FILE" ]]; then
  DOMAINS=$(< "$DOMAINS_FILE")
  dokku domains:set $APP $DOMAINS
fi
